### ISSUE TITLE
Error while trying to run any command

### ISSUE THREAD

**Issue by JamesKennewell** [Flibio/EconomyLite#54]
`[00:59:59] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'polis create bedrocktoiwn' for source EntityPlayerMP['iAmBedrock'/227, l='world', x=-34.48, y=102.36, z=230.32]: org/spongepowered/api/event/cause/EventContext
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/EventContext
	at io.github.flibio.economylite.CauseFactory.create(CauseFactory.java:34) ~[CauseFactory.class:?]
	at io.github.flibio.economylite.impl.economy.LiteEconomyService.getOrCreateAccount(LiteEconomyService.java:58) ~[LiteEconomyService.class:?]
	at io.github.hsyyid.polis.cmdexecutors.PolisCreateExecutor.execute(PolisCreateExecutor.java:55) ~[PolisCreateExecutor.class:2.7.0]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:182) ~[ChildCommandElementExecutor.class:1.11.2-6.1.0-BETA-20]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.11.2-6.1.0-BETA-20]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.11.2-6.1.0-BETA-20]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:296) ~[SpongeCommandManager.class:1.11.2-6.1.0-BETA-20]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:818) ~[mi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:805) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[ip.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[ip.class:?]
	at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:145) ~[PacketUtil.class:1.11.2-6.1.0-BETA-20]
	at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.11.2-6.1.0-BETA-20]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:144) [PacketUtil.class:1.11.2-6.1.0-BETA-20]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zji000(SourceFile:539) [fo$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:257) [SpongeImplHooks.class:1.11.2-6.1.0-BETA-20]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhh000(SourceFile:4188) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1527) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:335) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:562) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:466) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]`

I am getting this error while running any command, is this an issue with me possibly not having the right sponge api?

**Comment by Flibio** [comment]
What EconomyLite version are you using and what Sponge version?

**Comment by JamesKennewell** [comment]
Sponge : 1.11.2-6.1.0-BETA-20
EconomyLite 7.0.0-2.13.0

**Comment by Flibio** [comment]
Try using EconomyLite 2.12.0 for SpongeAPI 6, you are using a build for SpongeAPI 7.

**Comment by Flibio** [comment]
Closing due to inactivity.
