### ISSUE TITLE
Error when executing /baltop on MariaDB

### ISSUE THREAD

**Issue by BrainStone** [Flibio/EconomyLite#63]
When using the command `/baltop` while being connected to a MariaDB database (MariaDB is a MySQL fork and should be compatible. I doubt it's the issue though) I get the following error.

Using version: 2.13.0
SpongeForge: 1.12.2-2555-7.1.0-BETA-2844

```
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: java.sql.SQLSyntaxErrorException: (conn:237775) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''0', '6'' at line 1
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:158)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:245)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:167)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at io.github.flibio.economylite.utils.sql.SqlManager.executeQuery(SqlManager.java:141)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at io.github.flibio.economylite.utils.sql.SqlManager.queryTypeList(SqlManager.java:192)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at io.github.flibio.economylite.impl.PlayerServiceCommon.getTopAccounts(PlayerServiceCommon.java:112)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at io.github.flibio.economylite.commands.balance.BalTopCommand.run(BalTopCommand.java:87)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at io.github.flibio.economylite.utils.commands.BaseCommandExecutor.lambda$execute$0(BaseCommandExecutor.java:69)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [io.github.flibio.economylite.utils.sql.SqlManager:executeQuery:143]: at java.lang.Thread.run(Thread.java:748)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''0', '6'' at line 1
Query is: SELECT uuid FROM economyliteplayers WHERE currency = ? ORDER BY balance DESC LIMIT ?, ?, parameters ['economylite:coin','0','6']
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:223)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:212)
> [17:01:22] [pool-3-thread-77/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: ... 15 more
> [17:01:22] [pool-3-thread-77/ERROR] [economylite]: (conn:237775) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''0', '6'' at line 1
```

**Comment by Flibio** [comment]
The syntax for MariaDB is slightly different than the traditional MySQL one. I'm not currently planning on supporting a third database type. Is it possible to use a normal MySQL server?

**Comment by BrainStone** [comment]
You should use PreparedStatements in your code. This will work with MySQL and MariaDB.

I can have a look and try to fix it in a PR.

**Comment by Flibio** [comment]
I am already using PreparedStatements. See [this](https://github.com/FlibioStudio/Utils/blob/master/src/main/java/io/github/flibio/utils/sql/SqlManager.java#L137).

**Comment by BrainStone** [comment]
I see the issue. It's complaining that you try to set the limits with string values, when it's expecting integers.

I think you should use `setObject` instead of `setString` and `Object...` instead of `String...` in https://github.com/FlibioStudio/Utils/blob/master/src/main/java/io/github/flibio/utils/sql/SqlManager.java#L134-L147. Then the driver will autodetect the type. Also naturally pass the values in the correct type.

**Comment by Flibio** [comment]
That is a good point, I am not quite sure why I am using strings in the first place. I'm currently working on EconomyLite 3.0.0. I'm reworking some SQL stuff, so I'll include this change in their.

**Comment by BrainStone** [comment]
Would you mind to include this change in the current versions?

**Comment by Flibio** [comment]
I'll look into separating some of the 3.0.0 changes out into a smaller update that I will be able to release more quickly.

**Comment by ClarkHalf** [comment]
Economylite still don't work with mariadb ?

**Comment by ClarkHalf** [comment]
@BrainStone @Flibio

**Comment by BrainStone** [comment]
As you can see by this issue being closed and it being referenced by a commit, it has been resolved.
