### ISSUE TITLE
[2.14.3] NoSuchElementException on /pay

### ISSUE THREAD

**Issue by Rasgnarok** [Flibio/EconomyLite#83]
`[12:35:19] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error occured while tab completing 'pay _'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:284) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3151]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3987) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: Error occured while tab completing 'pay _'
	at org.spongepowered.common.command.SpongeCommandManager.getSuggestions(SpongeCommandManager.java:404) ~[SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3151]
	at net.minecraft.server.MinecraftServer.redirect$onGetTabCompletionOptions$zjg000(MinecraftServer.java:3755) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:920) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1347) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:147) ~[PacketUtil.class:1.12.2-2705-7.1.0-BETA-3151]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_171]
	at org.spongepowered.api.command.args.GenericArguments$UserCommandElement.getValue(GenericArguments.java:1154) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar:1.12.2-2705-7.1.0-BETA-3151]
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.Iterators$6.computeNext(Iterators.java:616) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[minecraft_server.1.12.2.jar:?]
	at org.spongepowered.api.command.args.CommandElement.parse(CommandElement.java:87) ~[CommandElement.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.api.command.args.GenericArguments$UserCommandElement.parse(GenericArguments.java:1178) ~[GenericArguments$UserCommandElement.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.api.command.args.GenericArguments$SequenceCommandElement.complete(GenericArguments.java:326) ~[GenericArguments$SequenceCommandElement.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.api.command.spec.CommandSpec.complete(CommandSpec.java:359) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.api.command.spec.CommandSpec.getSuggestions(CommandSpec.java:399) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:360) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.common.command.SpongeCommandManager.getSuggestions(SpongeCommandManager.java:390) ~[SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3151]
	at net.minecraft.server.MinecraftServer.redirect$onGetTabCompletionOptions$zjg000(MinecraftServer.java:3755) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:920) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1347) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:147) ~[PacketUtil.class:1.12.2-2705-7.1.0-BETA-3151]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more`

**Comment by Flibio** [comment]
What Sponge version are you using?

**Comment by 0Fox** [comment]
Same issue (Sponge - 1.12.2-2705-7.1.0-BETA-3148 / EL - 2.14.3) https://gist.githubusercontent.com/Zimon4eR/2d3c9cbe1a8b8b22b04934b1796daf9e/raw/aafe6920bd80a6458947e3b8fc2f96c8688c8665/16-06-2018_17-39-07.txt

Why do you ask sponge version? It's literally there
![](https://i.imgur.com/fAQNMVZ.png)

**Comment by Flibio** [comment]
I don't see EconomyLite mentioned in the error log anywhere, have you tried asking on the Sponge repository?

**Comment by Rasgnarok** [comment]
As you said, probably related to https://github.com/Flibio/EconomyLite/issues/88, and reported to SpongeCommon in https://github.com/SpongePowered/SpongeCommon/issues/1989

**Comment by Rasgnarok** [comment]
Likely related to https://github.com/SpongePowered/SpongeCommon/issues/1989#issuecomment-404639815, which is now closed. Closing this ticket, as if anything, it _was_ a Sponge issue!
