### ISSUE TITLE
[2.14.3] RuntimeException on tab-completing /pay

### ISSUE THREAD

**Issue by Rasgnarok** [Flibio/EconomyLite#88]
`[01:29:17] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error occured while tab completing 'pay H'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:284) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-0]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:3987) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: Error occured while tab completing 'pay H'
	at org.spongepowered.common.command.SpongeCommandManager.getSuggestions(SpongeCommandManager.java:404) ~[SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-0]
	at net.minecraft.server.MinecraftServer.redirect$onGetTabCompletionOptions$zjf000(MinecraftServer.java:3755) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:920) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1347) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:148) ~[PacketUtil.class:1.12.2-2705-7.1.0-BETA-0]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_171]
	at org.spongepowered.api.command.args.GenericArguments$UserCommandElement.getValue(GenericArguments.java:1155) ~[spongeforge-1.12.2-2705-7.1.0-BETA-PATREON1.jar:1.12.2-2705-7.1.0-BETA-0]
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.Iterators$6.computeNext(Iterators.java:616) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[minecraft_server.1.12.2.jar:?]
	at org.spongepowered.api.command.args.CommandElement.parse(CommandElement.java:87) ~[CommandElement.class:1.12.2-2705-7.1.0-BETA-0]
	at org.spongepowered.api.command.args.GenericArguments$UserCommandElement.parse(GenericArguments.java:1179) ~[GenericArguments$UserCommandElement.class:1.12.2-2705-7.1.0-BETA-0]
	at org.spongepowered.api.command.args.GenericArguments$SequenceCommandElement.complete(GenericArguments.java:326) ~[GenericArguments$SequenceCommandElement.class:1.12.2-2705-7.1.0-BETA-0]
	at org.spongepowered.api.command.spec.CommandSpec.complete(CommandSpec.java:359) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-0]
	at org.spongepowered.api.command.spec.CommandSpec.getSuggestions(CommandSpec.java:399) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-0]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:360) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-0]
	at org.spongepowered.common.command.SpongeCommandManager.getSuggestions(SpongeCommandManager.java:390) ~[SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-0]
	at net.minecraft.server.MinecraftServer.redirect$onGetTabCompletionOptions$zjf000(MinecraftServer.java:3755) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:920) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1347) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:148) ~[PacketUtil.class:1.12.2-2705-7.1.0-BETA-0]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more`

**Comment by Flibio** [comment]
Like I said in your previous issue, have you posted this to the Sponge issue page? EconomyLite is never once mentioned in the error log although the pay command belongs to EconomyLite. It may be a Sponge issue.

**Comment by Rasgnarok** [comment]
It could be, I'll ask - I only seem to have issues with `/pay` though, which is why I first ticketed it here.

**Comment by Rasgnarok** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1989

**Comment by Flibio** [comment]
Thanks for letting me know.

**Comment by dualspiral** [comment]
Yes, it's a Sponge issue.

**Comment by Rasgnarok** [comment]
Will be testing again now that https://github.com/SpongePowered/SpongeCommon/issues/1989#issuecomment-404639815 is closed,  but the test version I tried out for dual worked. Closing this ticket, as if anything, it _was_ a Sponge issue!
